[env:esp32-s3-super-mini]
platform  = espressif32@6.8.1
board     = esp32-s3-devkitc-1
framework = arduino

board_build.flash_mode  = qio
board_upload.flash_size = 4MB
board_build.partitions  = default.csv

build_unflags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=0

build_flags =
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=0

monitor_speed   = 115200
monitor_filters = esp32_exception_decoder

lib_deps =
    h2zero/NimBLE-Arduino @ 1.4.3
